#!/usr/bin/env bash
# Transfers a file from client to server


# Function to display usage instructions
display_usage() {
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

# Check if number of arguments is less than 4, display usage if so
if [ "$#" -lt 4 ]; then
	display_usage
	exit 1
fi

# Assigning command line arguments to variables
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Checking if the file exists
if [ ! -f "$PATH_TO_FILE" ]; then
	echo "Error: File '$PATH_TO_FILE' does not exist."
	exit 1
fi

# Using scp to transfer the file to the server
scp -o StrictHostKeyChecking=no \
	-i "$PATH_TO_SSH_KEY" \
	"$PATH_TO_FILE" \
	"$USERNAME"@"$IP":~/

# Checking the exit status of scp command
if [ "$?" -ne 0 ]; then
	echo "Error: FIle transfer failed."
	exit 1
else
	echo "File '$PATH_TO_FILE' transferred successfully to $USERNAME@$IP:~/"
fi

exit 0
