#!/usr/bin/env bash
# A script that installs nginx and start the service.

# Update package index
apt-get update

# Install nginx
apt-get -y install nginx

# Ensure nginx is running.
service nginx start

# Configure nginx to serve "Hello world" at root /
echo "Hello World!" > /var/www/html/index.html

# Restart nginx without using systemctl
/etc/init.d/nginx reload > /dev/null

# Verification: Check if nginx is listening on port 80
netstat -tnl | grep ':80 '> /dev/null
if [ $? -ne 0 ]; then
	echo "Nginx is not listening on port 80. \
		Please check nginx configuration."
	exit 1
fi

# Cleanup: Remove default nginx index.html file
rm /var/www/html/index.nginx-debian.html

echo "Nginx installed and configured successfully!"
