#!/usr/bin/env bash
# Configures the Nginx server so that /redirect_me is redirecting to another page.

# Update the package list and install Nginx
apt-get update
apt-get install nginx

# Allow Nginx through the firewall
ufw allow 'Nginx HTTP'

# Create the web root directory and set permissions
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www

# Create a simple HTML file
echo 'Hello World!' > /var/www/html/index.html

# Define the direction configuration
REDIRECT_CONFIG="
	rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	"

# Define the redirection configuration to the existing server block \
# in the default site configuration.
sed -i '/server_name _;/a $REDIRECT_CONFIG' /etc/nginx/sites-available/default

#Check Nginx configuration syntax
sudo nginx -t

# Restart Nginx to apply the changes
service nginx start
