#!/usr/bin/env bash
# Installs HAproxy

# Function to check if the previous command was successful
check_success() {
	if [ $? -ne 0 ]; then
		echo "Error: $1 failed.  Exiting..."
		exit 1
	fi
}

# Update and upgrade the system
echo -e "\n\n\nUpdating and upgrading the system...\n\n\n"
apt update && apt upgrade -y
check_success "System update and upgrade"

# Update and install necessary tools
echo -e "\n\nInstalling software-properties-common...\n\n\n"
apt-get install --no-install-recommends software-properties-common
check_success "Installation of software-properties-common"

# Add the PPA for the latest HAProxy version
echo -e "\n\nAdding PPA for HAProxy...\n\n\n"
add-apt-repository ppa:vbernat/haproxy-2.8 -y
check_success "Adding PPA for HAProxy"

# Update package list to include new PPA
echo -e "\n\nUpdating package list...\n\n\n"
sudo apt-get update
check_success "Updating package list"

# Install the specific version of the HAproxy
echo -e "\n\nInstalling HAProxy version 2.8...\n\n\n"
apt-get install haproxy=2.8.\* -y
check_success "Installation of HAProxy"

# Backup the original HAProxy configuration file
echo -e "\n\nBacking up original HAProxy configuration...\n\n\n"
cp /etc/haproxy/haproxy.cfg{,.orig}	# same with cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.orig
check_success "Backup of HAProxy configuration"

# Overwrite the HAproxy configuration file with new settings
echo -e "\n\nApplying new HAProxy configuration...\n\n\n"
echo -e "\nfrontend D3MXN-W3B\n\tbind *:80\n\tmode http\n\tdefault_backend D3MXN-BVCK3ND\n\nbackend D3MXN-BVCK3ND\n\tbalance roundrobin\n\tserver 471347-web-01 3.85.141.115:80 check\n\tserver 471347-web-02 54.237.55.254:80 check" >> /etc/haproxy/haproxy.cfg
check_success "Application of HAProxy configuration"

# Ensure HAProxy is enabled
echo -e "\n\nEnsuring HAProxy is enabled...\n\n\n"
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
check_success "Enabling HAProxy"

# Restart HAproxy to apply the new configuration
echo "\n\nRestarting HAProxy...\n\n\n"
service haproxy restart
check_success "Restarting HAProxy"


echo "\n\n\nHAProxy installation and configuration complete.\n\n\n"
