#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it.

# Check if the correct number of arguments is provided
if [[ "$#" -ne 1 ]]; then
    echo "Usage: $0 <mysql_pwd>"
    exit 1
fi

mysql_pwd=$1
file="backup.sql"
date_format=$(date +"%d-%m-%Y")
archive_file="${date_format}.tar.gz"

# Check if mysqldump and tar commands are available
command -v mysqldump >/dev/null 2>&1 || { echo "mysqldump command not found. Please install it."; exit 4; }
command -v tar >/dev/null 2>&1 || { echo "tar command not found. Please install it."; exit 5; }

# Generate MySQL dump
sudo mysqldump -u root -p"${mysql_pwd}" --all-databases > "${file}"

# Check if mysqldump was successful
if [ $? -ne 0 ]; then
    echo "MySQL dump failed."
    exit 2
fi

# Compress the backup file
tar -czvf "${archive_file}" "${file}"

# Check if tar compression was successful
if [ $? -ne 0 ]; then
    echo "Compression failed."
    exit 3
fi

# Clean up the backup file
#rm "${file}"

# Confirm successful backup and compression
echo "Backup and compression completed successfully. File saved as ${archive_file}."
