#!/usr/bin/env bash
# Enables the default Nginx configuration and starts the service
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
