#!/usr/bin/env bash
# Tells the story of passwd

while IFS=":" read -r username password userid _ _ homedir shell; do
	# Extract the first character of the password field (usually "x")
	#password=$(getent passwd "$username" | cut -d ':' -f2 | cut -c 1)

	# Display formatted information about the user.
	echo "The user $username is part of the $userid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $username"
done < /etc/passwd
