#!/usr/bin/env bash
# Display all active IPv4 IPs on the machine

# Use ifconfig to get the IP addresses and filter out IPv6 addresses
# Then use grep to extract only the lines containing 'inet'
# Finally, use awk to print the second field (the IP address)
ifconfig | grep 'inet ' | awk '{print $2}'
